# Generated by Django 3.0.3 on 2020-03-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatamod',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='app'),
        ),
        migrations.AlterField(
            model_name='userdatamod',
            name='user_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
