# Generated by Django 3.0.3 on 2020-03-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='name',
            new_name='namere',
        ),
    ]
