# Generated by Django 3.0.3 on 2020-03-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200311_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='namere',
            new_name='urle',
        ),
    ]
