# Generated by Django 3.0.3 on 2020-03-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200311_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
